import "package:myapp/domain/class.dart";

final List<Song> songs = [
  Song(
    id: '1',
    title: 'Somethin\' Stupid',
    singer: 'Frank Sinatra & Nancy Sinatra',
    year: 1967,
    posterUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/d722c2511d6aee22bee0bd6144f1519d.jpg',
  ),
  Song(
    id: '2',
    title: 'Walk',
    singer: 'NCT 127',
    year: 2024,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/NCT_127_-_Walk.png/250px-NCT_127_-_Walk.jpg',
  ),
  Song(
    id: '3',
    title: 'Bite Me',
    singer: 'Enhypen',
    year: 2023,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Enhypen_-_Dark_Blood.jpg/250px-Enhypen_-_Dark_Blood.jpg',
  ),
  Song(
    id: '4',
    title: 'Ice on My Teeth',
    singer: 'ATEEZ',
    year: 2024,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Golden_Hour_Part.2_cover.png/250px-Golden_Hour_Part.2_cover.jpg',
  ),
  Song(
    id: '5',
    title: 'Freak on a Leash',
    singer: 'Korn',
    year: 1998,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Freakonaleash.jpg/250px-Freakonaleash.jpg',
  ),
  Song(
    id: '6',
    title: 'Twist',
    singer: 'Korn',
    year: 1996,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Korn-LifeIsPeachy.jpg/250px-Korn-LifeIsPeachy.jpg',
  ),
  Song(
    id: '7',
    title: 'We Don\'t Talk Anymore',
    singer: 'Charlie Puth feat. Selena Gomez',
    year: 2016,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Charlie_Puth_Feat._Selena_Gomez_-_We_Don%27t_Talk_Anymore_%28Official_Single_Cover%29.png/250px-Charlie_Puth_Feat._Selena_Gomez_-_We_Don%27t_Talk_Anymore_%28Official_Single_Cover%29.jpg',
  ),
  Song(
    id: '8',
    title: 'Cachita',
    singer: 'Lisa Ono',
    year: 2005,
    posterUrl: 'https://images.genius.com/f739c489c7ca24791f1e26bb1da8d194.1000x1000x1.jpg',
  ),
  Song(
    id: '9',
    title: 'XO (Only If You Say Yes)',
    singer: 'Enhypen',
    year: 2024,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Enhypen_-_Romance_Untold_Daydream.png/250px-Enhypen_-_Romance_Untold_Daydream.jpg',
  ),
  Song(
    id: '10',
    title: 'Shape Of You',
    singer: 'Ed Sheeran',
    year: 2017,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png/250px-Shape_Of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.jpg',
  ),
  Song(
    id: '11',
    title: 'Treat You Better',
    singer: 'Shawn Mendes',
    year: 2016,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Treat_You_Better_%28Official_Single_Cover%29_by_Shawn_Mendes.png/250px-Treat_You_Better_%28Official_Single_Cover%29_by_Shawn_Mendes.jpg',
  ),
  Song(
    id: '12',
    title: 'Sorry',
    singer: 'Justin Bieber',
    year: 2015,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/8/8e/Sorry_Justin_Bieber_Capa.png?20151209214800.jpg',
  ),
  Song(
    id: '13',
    title: 'Daylight',
    singer: 'David Kushner',
    year: 2023,
    posterUrl: 'https://akamai.sscdn.co/uploadfile/letras/fotos/7/0/c/2/70c24a8dc8728363c7ae7a7c223a14fe.jpg',
  ),
];
