import "package:myapp/domain/class.dart";

final List<Song> songs = [
  Song(
    id: '1',
    title: 'Somethin\' Stupid',
    singer: 'Frank Sinatra & Nancy Sinatra',
    year: 1967,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Something_Stupid_single_cover.jpg',
  ),
  Song(
    id: '2',
    title: 'Walk',
    singer: 'NCT 127',
    year: 2024,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3e/NCT_127_-_Walk.png',
  ),
  Song(
    id: '3',
    title: 'Bite Me',
    singer: 'Enhypen',
    year: 2023,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Enhypen_-_Dark_Blood.png',
  ),
  Song(
    id: '4',
    title: 'Ice on My Teeth',
    singer: 'ATEEZ',
    year: 2024,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Ateez_-_Golden_Hour_Part_2.png',
  ),
  Song(
    id: '5',
    title: 'Freak on a Leash',
    singer: 'Korn',
    year: 1998,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Korn_-_Follow_the_Leader.png',
  ),
  Song(
    id: '6',
    title: 'Twist',
    singer: 'Korn',
    year: 1996,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Korn_-_Life_Is_Peachy.png',
  ),
  Song(
    id: '7',
    title: 'We Don\'t Talk Anymore',
    singer: 'Charlie Puth feat. Selena Gomez',
    year: 2016,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Charlie_Puth_-_Nine_Track_Mind.png',
  ),
  Song(
    id: '8',
    title: 'Cachita',
    singer: 'Lisa Ono',
    year: 2005,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Lisa_Ono_-_Bossa_Latino.png',
  ),
  Song(
    id: '9',
    title: 'El Pollito Pío',
    singer: 'Los Meñiques de la Casa',
    year: 2012,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2a/El_Pollito_P%C3%ADo_album_cover.png',
  ),
  Song(
    id: '10',
    title: 'Back To Me',
    singer: 'The Rose',
    year: 2023,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/The_Rose_-_Dual.png',
  ),
  Song(
    id: '11',
    title: 'Treat You Better',
    singer: 'Shawn Mendes',
    year: 2016,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f7/Shawn_Mendes_-_Treat_You_Better.png',
  ),
  Song(
    id: '12',
    title: 'Sorry',
    singer: 'Justin Bieber',
    year: 2015,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6d/Justin_Bieber_-_Purpose_%28Official_Album_Cover%29.png',
  ),
  Song(
    id: '13',
    title: 'Daylight',
    singer: 'David Kushner',
    year: 2023,
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5e/David_Kushner_-_The_Dichotomy.png',
  ),
];
